name: Delete deployed PR from S3
on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  delete_deployed_pr:
    runs-on: ubuntu-latest
    # PRs are only deployed if the PR branch is not in a fork
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
      - run: aws --endpoint-url https://s3.cern.ch s3 rm --recursive s3://root/${PR_NUMBER:?}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-1"
          PR_NUMBER: ${{ github.event.pull_request.number }}
