name: HTML proofer

on:
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Jekyll Action
      uses: root-project/jekyll-action@HEAD

    - name: Install HTML proofer
      run: sudo apt install ruby && sudo gem install html-proofer
    
    - name: Run HTML proofer
      # Don't check release pages and pagination pages
      run: htmlproofer --empty-alt-ignore --file-ignore "/(releases|page.?/index.html)/" --disable-external build
