name: HTML proofer

on:
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Jekyll Action
      uses: root-project/jekyll-action@HEAD
    
    - name: Run HTML proofer
      uses: chabad360/htmlproofer@v1.1
      with:
          directory: "./build"
          # Reasons for url-ignore
          # - ourselves: Breaks checking local builds due to links in the metadata
          # - rootbnch-grafana-test.cern.ch: Breaks due to SSO
          # - lcgapp-services.cern.ch: Breaks due to SSO
          # - indico.desy.de: Returns frequently error code 403
          arguments: --empty-alt-ignore --file-ignore "/(releases|page.?/index.html)/" --allow-hash-href --url-ignore "/(https://ph-root-2.cern.ch/.*|https://rootbnch-grafana-test.cern.ch|https://lcgapp-services.cern.ch/root-jenkins|https://indico.desy.de.*)/"
