name: HTML proofer

on:
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Jekyll Action
      uses: root-project/jekyll-action@HEAD
    
    - name: Run HTML proofer
      uses: chabad360/htmlproofer@v1.1
      with:
          directory: "./build"
          arguments: --empty-alt-ignore --file-ignore "/(releases|page.?/index.html)/" --allow-hash-href --url-ignore "/https://ph-root-2.cern.ch/.*/"
