name: Link Checker

# Run on push to gh-pages and for PRs
on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:
    name: Link Checker
    # Run with ubuntu latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Jekyll Action
      uses: root-project/jekyll-action@HEAD
      
    - name: Link Checker
      uses: peter-evans/link-checker@v1
      with:
        # liche arguments (https://github.com/raviqqe/liche)
        args: -x savannah.cern.ch -v -r build
    
    - uses: actions/upload-artifact@v2
      with:
        name: Report
        path: link-checker/out.md
